name: zip
description: The premier solution for gameday travel needs modeled after the successes of Uber and Lyft.
version: 0.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.2
  cloud_firestore: ^0.13.4+2
  cloud_functions: ^0.4.2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.2.0+2
  font_awesome_flutter: 8.4.0
  google_sign_in: ^4.4.0
  flutter_facebook_login: ^3.0.0
  shared_preferences: ^0.5.6+3
  flutter_swiper: ^1.1.6
  google_maps_flutter: ^0.5.11
  geolocator: ^5.3.1
  location_permissions: ^2.0.4+1
  percent_indicator: ^2.1.1+1
  modal_progress_hud: ^0.1.2
  image_picker: 0.6.3+4
  firebase_storage: ^3.1.5
  flutter_polyline_points: ^0.1.0
  maps_launcher: ^1.2.0
  webview_flutter: ^0.3.19+9
  geoflutterfire: ^2.1.0
  flutter_google_places: ^0.2.4
  google_maps_webservice: ^0.0.16

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: 0.7.0
  flutter_auth_buttons: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  rxdart:
  flutter_automation: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  # - assets/mountains.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
